CREATE TABLE inmet.dados_estacoes
(
    id              SERIAL PRIMARY KEY,
    estacao         TEXT NOT NULL,
    data            DATE NOT NULL,
    utc             TEXT NOT NULL,
    temperatura     DECIMAL,
    temperatura_min DECIMAL,
    temperatura_max DECIMAL,
    umidade         DECIMAL,
    umidade_min     DECIMAL,
    umidade_max     DECIMAL,
    pto_orvalho     DECIMAL,
    pto_orvalho_min DECIMAL,
    pto_orvalho_max DECIMAL,
    pressao         DECIMAL,
    pressao_min     DECIMAL,
    pressao_max     DECIMAL,
    vento           DECIMAL,
    vento_dir       DECIMAL,
    vento_raj       DECIMAL,
    radiacao        DECIMAL,
    chuva           DECIMAL,
    CONSTRAINT dados_estacoes_momento_uk UNIQUE (estacao, data, utc)
);
